[pytest]
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:pydantic.v1.typing
    ignore::DeprecationWarning:pyasn1.codec.ber.encoder
    ignore::DeprecationWarning:phoenix.evals
    ignore::DeprecationWarning:strawberry.fastapi.router
    ignore::DeprecationWarning:pydantic._internal._generate_schema
    ignore:.*json_encoders.*:pydantic.warnings.PydanticDeprecatedSince20
