from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
import requests

class SimpleLoginClient:
    """
    Client for managing persistent email aliases via SimpleLogin.
    Fetches API key from Azure Key Vault at runtime.
    """
    def __init__(self, vault_url: str):
        self.credential = DefaultAzureCredential()
        self.client = SecretClient(vault_url=vault_url, credential=self.credential)
        self.api_key = self.client.get_secret("SimpleLoginApiKey").value
        self.base_url = "https://app.simplelogin.io/api"
        self.headers = {"Authentication": f"Bearer {self.api_key}"}

    def create_alias(self, mailbox_id: int, prefix: str):
        """Creates a new persistent alias for a specific persona."""
        endpoint = f"{self.base_url}/v4/mailbox/{mailbox_id}/alias"
        data = {"prefix": prefix, "note": "Generated by Ghidorah Mesh"}
        
        response = requests.post(endpoint, headers=self.headers, json=data)
        return response.json()

# Implementation Example:
# sl_client = SimpleLoginClient("https://your-vault-name.vault.azure.net/")
# new_alias = sl_client.create_alias(mailbox_id=123, prefix="ghost_alpha_01")